# name is used for the logo image alt text, and in the footer copyright
name: ProLabPrints.com
title: ProLabPrints.com ROES
description: ProLabPrints.com ROES Ordering System
# baseurl is used if you are using github pages for a project page - this is the project/repo name, always starts with a /
baseurl: /plp-splash17 


permalink: pretty
exclude: ["Gemfile.lock","Gemfile","package.json","rakefile.rb","README.md","s3_website.yml","node_modules","gulpfile.js"]
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

# Google analytics ID - uncomment and add your GA ID
# ga: UA-xxxx-yy

# cannonical_domain is used for building the full url to your site including the domain and base_url if any.
# it is used in the sitemap.xml, robots.txt and in the head of every page as a link rel="canonical" tag.
# do not include the baser_url if any as it is added in when building the link.
# DO NOT leave it empty or comment it out! or your sitemap and robots files will be incorrect. 
# what is the url google will find the main site at - not including base_url if any? 
canonical_domain: http://rdyar.github.io

# image for logo, if you don't have one comment it out and use the logo_text below.
logo_url: /assets/images/pro-lab-prints-logo14.png

# if no logo, comment out above and enter the name and it will show instead
# if the logo_url above is used this will not display
logo_text: ProLabPrints.com

# Main nav is for screens wider than 600px
# Home link is hard coded by default
main_nav:
  - title: "Support"
    url: /support/
 
# on screens smaller than 600px, what nav do you want to show?
# Home is not set by default, the logo works as home link so it could be skipped.
# mobile nav is shown as buttons, there is room for 3-5 depending on how long they are.
mobile_nav:
  - title: Home
    url: /
  
# Expander footer - this has 3 sections, about, links and contact info.
# if you don't need the expanded footer info change this to false.
expanded_footer: true

# expanded footer about section. If you have a large site myou should probably hard code these in the footer include.
# the title is wrapped in an h2 tag
# the content part is wrapped in a p tag. It is ok to have html in it, just be aware of the already included p tag
# important! - you cannot use site.base_url or any other site variables in the content! notice I have hard coded my base_url
ef_about:
  heading: ProLabPrints.com ROES
  content: >
        Cleverly hidden in a tiny strip mall in San Diego, we are a small team of friendly, highly trained professionals doing our best to make your images come to life.
# Links section - if they are relative then use url, if they are absolute (different domain) use absolute_url
ef_links:
 # heading: Links
  links:
   #- title: Go To ProLabPrints.com Website
   #  external_url: https://prolabprints.com/

ef_contact:
  heading: Contact Info
  content: >
          ProLabPrints.com / Fromex Photo Lab, Inc.<br />
          6370 El Cajon Blvd <br />
          San Diego, CA 92115 <br />
          Hours: Monday - Friday 9am-6pm<br />
          Phone: (619) 287-5346<br />
# shows link to strapless on GH
show_footer_credit: true
