- title: Canvas Gallery Wraps
  icon: canvas-gallery-wraps.jpg
  url: /services/canvas-gallery-wraps/
  featured: core
  description: Ready to hang wall art

- title: Press Prints on Cardstock
  icon: press-prints-card-stock.jpg
  url: /services/press-printed-products/
  description: "Flat, folded, trifold..."
  featured: core

- title: Prints on Metal
  icon: metal-prints.jpg
  url: /services/prints-on-metal/
  description: "Stunning! Your image on aluminum"
  featured: core

- title: Scrapbook Printing
  icon: scrapbook-prints.jpg
  url: /digital-printing/scrapbook-printing/
  featured: normal
  description: "3x4 up to 12x12 prints and templates"

- title: Fuji Pearl Prints
  icon: "pearl-prints-icon.jpg" 
  url: "/services/digital-prints/"
  featured: core
  description: "High gloss metalic photo paper"

- title: Package Printing
  icon: units-and-package-printing.jpg
  url: /digital-printing/package-printing/
  featured: core
  description: "Printing for sports, schools, proms etc"    

- title: Die Cut Wallets
  icon: die-cut-wallets.jpg
  url: /services/die-cut-wallets/
  featured: normal
  description: Die Cut Wallets with rounded corners


# - title: Double Sided Greeting Cards
#   icon: double-sided-greeting-cards.jpg
#   url: /services/double-sided-greeting-cards/
#   description: "Double sided greeting cards on Card Stock."
#   featured: normal

# - title: Traditional Photo Greeting Cards
#   icon: traditional-photo-greeting-cards.jpg
#   url: /services/traditional-photo-greeting-cards/
#   description: "Single sided 4x8 and 5x7 photo greeting cards."
#   featured: normal

#- title: Photo Calendars
# icon: photo-calendars.jpg
# url: /services/custom-photo-calendars/
# description: "Photo Calendars make a great gift idea!"
# featured: normal  

- title: 8x10 Headshots
  icon: 8x10-headshots.jpg
  url:  /services/8x10-headshots/
  description: "8x10 templates with your name"
  featured: normal


- title: Locket Prints
  icon: locket-prints.jpg
  url: /services/locket-photo-prints/
  description: Our take on solving the locket print problem - 25 different sizes on a 5x7
  featured: normal

- title: Prints on Tile
  icon: prints-on-tile.jpg
  url: /services/prints-on-tile/
  description: "Your photo on a ceramic tile. 4x4, 6x6 and 8x8 sizes available"
  featured: normal

- title: Quantity 8x10 Prints
  icon: quantity-8x10-prints.jpg
  url: /services/quantity-8x10-prints/
  description: Need a large number of 8x10s for autographs?
  featured: normal

- title: Passport Photos
  icon: passport-photos.jpg
  url:  /services/passport-photos/
  description: "DIY passport photo"
  featured: instore
